/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./counties.html",
    "./red-flags.html",
    "./contract.html",
    "./methodology.html",
    "./reports.html",
    "./mobile.html",
    "./src/**/*.{js,ts,jsx,tsx,css}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#63578a",
        "on-background": "#1a1c1b",
        "surface-tint": "#7f5602",
        "secondary-fixed-dim": "#a8cfc2",
        "on-primary-fixed-variant": "#614000",
        "on-error": "#ffffff",
        "outline": "#817566",
        "extreme-crimson": "#9E1B1B",
        "tertiary-fixed": "#e8deff",
        "surface-container-high": "#e9e8e6",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#281800",
        "inverse-on-surface": "#f1f1ef",
        "surface-variant": "#e3e2e0",
        "tertiary-fixed-dim": "#cdbef9",
        "secondary": "#42655b",
        "on-surface-variant": "#4f4537",
        "on-tertiary-container": "#372c5c",
        "error": "#ba1a1a",
        "secondary-fixed": "#c4ebde",
        "on-primary-container": "#482f00",
        "amber-warning": "#FF8F00",
        "on-secondary-fixed": "#002019",
        "primary-fixed": "#ffddaf",
        "surface-container": "#efeeec",
        "paper-white": "#FCFBFA",
        "surface-container-highest": "#e3e2e0",
        "primary": "#7f5602",
        "primary-container": "#c59341",
        "inverse-surface": "#2f3130",
        "primary-fixed-dim": "#f4bd67",
        "on-error-container": "#93000a",
        "on-secondary-container": "#466a5f",
        "surface-container-low": "#f4f3f1",
        "savannah-green": "#1A3E35",
        "inverse-primary": "#f4bd67",
        "secondary-container": "#c1e8db",
        "on-tertiary-fixed": "#1e1242",
        "on-secondary-fixed-variant": "#2a4d44",
        "on-secondary": "#ffffff",
        "surface-dim": "#dadad8",
        "on-surface": "#1a1c1b",
        "on-tertiary-fixed-variant": "#4b3f71",
        "surface-bright": "#faf9f7",
        "surface-container-lowest": "#ffffff",
        "surface": "#faf9f7",
        "civic-gold": "#C59341",
        "on-tertiary": "#ffffff",
        "background": "#faf9f7",
        "outline-variant": "#d3c4b2",
        "dominant-orange": "#E65100",
        "error-container": "#ffdad6",
        "midnight-slate": "#121417",
        "tertiary-container": "#a194cc"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-edge": "32px",
        "gutter": "24px",
        "unit": "4px",
        "container-max": "1280px"
      },
      fontFamily: {
        "headline-md": ["\"Source Serif 4\""],
        "body-lg": ["Public Sans"],
        "label-caps": ["Public Sans"],
        "headline-lg-mobile": ["\"Source Serif 4\""],
        "headline-lg": ["\"Source Serif 4\""],
        "display-lg": ["\"Source Serif 4\""],
        "body-md": ["Public Sans"],
        "data-mono": ["Public Sans"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-mono": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
